# Generated by Django 3.2.6 on 2021-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentmodels',
            name='segment_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hostmodels',
            name='kinds',
            field=models.CharField(choices=[('server', 'サーバ'), ('network', 'ルータ/スイッチ'), ('client/static', 'クライアント/静的割当'), ('client/DHCP', 'クライアント/DHCP'), ('gateway', 'ゲートウェイ'), ('other', 'その他機器')], max_length=30),
        ),
    ]
