# Generated by Django 3.2.6 on 2021-09-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipledger', '0002_auto_20210908_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentmodels',
            name='nw_address',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
