# Generated by Django 3.2.6 on 2021-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipledger', '0003_alter_segmentmodels_nw_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentmodels',
            name='nw_address',
            field=models.CharField(max_length=15, unique=True, verbose_name='ネットワークアドレス'),
        ),
        migrations.AlterField(
            model_name='segmentmodels',
            name='prefix',
            field=models.IntegerField(verbose_name='プレフィックス長'),
        ),
        migrations.AlterField(
            model_name='segmentmodels',
            name='seg_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ネットワークの説明'),
        ),
        migrations.AlterField(
            model_name='segmentmodels',
            name='segment_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ネットワーク名'),
        ),
    ]
